---
- name: Update Ubuntu apt sources list
  hosts: all
  become: true

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: /etc/apt/sources.list.bak
        state: directory
        mode: '0755'

    - name: Backup the current sources.list
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list.bak/sources.list-{{ ansible_date_time.iso8601 }}

    - name: Check if /etc/apt/sources.list.d exists
      stat:
        path: /etc/apt/sources.list.d
      register: sources_list_d

    - name: Backup the current sources.list.d directory if it exists
      archive:
        path: /etc/apt/sources.list.d
        dest: /etc/apt/sources.list.bak/sources.list.d-{{ ansible_date_time.iso8601 }}.tar.gz
        format: gz
      when: sources_list_d.stat.exists

    - name: Remove the sources.list.d directory if it exists
      file:
        path: /etc/apt/sources.list.d
        state: absent
      when: sources_list_d.stat.exists

    - name: Replace sources.list with new content
      copy:
        content: |
          # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
          # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
          # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse
          # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse

          # 以下安全更新软件源包含了官方源与镜像站配置，如有需要可自行修改注释切换
          deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
          # deb-src http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse

          # 预发布软件源，不建议启用
          # deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
          # # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-proposed main restricted universe multiverse
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0666'

- name: Update Ubuntu apt sources list
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
...