- name: Install OpenEBS via sealos
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Set sealos command
      set_fact:
        sealos_command: echo y | sealos run labring/openebs:v3.10.0

    - name: Debug sealos command
      debug:
        msg: "{{ sealos_command }}"

    - name: Run sealos command
      shell: "{{ sealos_command }}"
      environment:
        http_proxy: "{{ hostvars['main']['proxy'] }}"
        https_proxy: "{{ hostvars['main']['proxy'] }}"