---
- name: Cleanup Gearbox on worker nodes
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Remove the gearbox eBPF programs by deleting directory
      file:
        path: "/sys/fs/bpf/gearbox"
        state: absent

    - name: Clean Gearbox
      shell: |
        cd /root/microservice-failure-analysis/framework/feature/gearbox
        make clean
      args:
        executable: /bin/bash

- name: Cleanup gearbox controller tmux session
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Check if tmux session exists
      shell: tmux has-session -t gearbox_controller
      register: tmux_session_check
      ignore_errors: yes
  
    - name: Kill tmux session if it exists
      shell: tmux kill-session -t gearbox_controller
      when: tmux_session_check.rc == 0

- name: Cleanup gearbox agent tmux session
  hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - name: Check if tmux session exists
      shell: tmux has-session -t gearbox_agent
      register: tmux_session_check
      ignore_errors: yes
  
    - name: Kill tmux session if it exists
      shell: tmux kill-session -t gearbox_agent
      when: tmux_session_check.rc == 0
...