- name: Cleanup Gearbox on worker nodes
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Remove the gearbox eBPF directory
      file:
        path: "/sys/fs/bpf/gearbox"
        state: absent

    - name: Clean Gearbox
      shell: |
        cd /root/microservice-failure-analysis/framework/feature/gearbox
        make clean
      args:
        executable: /bin/bash
