---
# - import_playbook: ./update_repo.yml
- import_playbook: ./cleanup.yml

- name: Compile and Run Gearbox on worker nodes
  hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - name: Compile Gearbox
      shell: make > /tmp/gearbox-build.log
      args:
        chdir: /root/microservice-failure-analysis/framework/feature/gearbox
        executable: /bin/bash

    - name: Load Gearbox eBPF kernel program with loader-capsule
      shell: ./loader-capsule > /tmp/loader-capsule.log
      args:
        chdir: /root/microservice-failure-analysis/build/gearbox
        executable: /bin/bash

- import_playbook: ./update_pid.yml
- import_playbook: ./update_config.yml

- name: Run gearbox controller
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Remove the gearbox controller output file
      file:
        path: "/root/microservice-failure-analysis/framework/feature/gearbox/output/raw_data.log"
        state: absent

    - name: Run controller
      shell: tmux new-session -d -s gearbox_controller 'python3 ./controller.py -f ../config/config.json; sleep 10000000000'
      args:
        chdir: /root/microservice-failure-analysis/framework/feature/gearbox/server
        executable: /bin/bash

- name: Run gearbox agent
  hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - name: Run agent
      shell: tmux new-session -d -s gearbox_agent './agent -c ../../framework/feature/gearbox/config/config.json -p ../../framework/feature/gearbox/output/pid.txt -d 2; sleep 10000000000'
      args:
        chdir: /root/microservice-failure-analysis/build/gearbox
        executable: /bin/bash
...