---
- name: Cleanup Helm installations
  hosts: controller
  gather_facts: no
  tasks:
    - name: Attempt to uninstall hotelReservation Helm release
      command: helm uninstall hotel
      ignore_errors: yes
      register: hotelReservation_uninstall_result

    - name: Debug hotelReservation Helm uninstall result
      debug:
        var: hotelReservation_uninstall_result["stdout_lines"]

    - name: Attempt to uninstall mediaMicroservices Helm release
      command: helm uninstall media
      ignore_errors: yes
      register: mediaMicroservices_uninstall_result

    - name: Debug mediaMicroservices Helm uninstall result
      debug:
        var: mediaMicroservices_uninstall_result["stdout_lines"]

    - name: Attempt to uninstall socialNetwork Helm release
      command: helm uninstall social
      ignore_errors: yes
      register: socialNetwork_uninstall_result

    - name: Debug socialNetwork Helm uninstall result
      debug:
        var: socialNetwork_uninstall_result["stdout_lines"]

    - name: Attempt to cleanup workload deployment
      shell: kubectl delete deployment deathstar-workload-job
      ignore_errors: yes
    
    - name: Attempt to cleanup workload job
      shell: kubectl delete job deathstar-workload-job
      ignore_errors: yes