---
- name: Register Users and Construct Social Graphs
  hosts: controller
  vars_files:
    - ../../shared_vars.yaml
  vars:
    timestamp: "{{ ansible_date_time.iso8601_basic }}"
    docker_image: deathstar-workload:latest
    job_yaml_path: "/tmp/DeathStar-workload-job.yaml"
    job_name: deathstar-workload-job

    luarocks_url: "https://luarocks.org/releases/luarocks-3.11.1.tar.gz"
    luarocks_tar: "/tmp/luarocks-3.11.1.tar.gz"

  tasks:
    - name: Download LuaRocks
      get_url:
        url: "{{ luarocks_url }}"
        dest: "{{ luarocks_tar }}"

    - name: Create Docker image
      include_role:
        name: ../../roles/docker_builder
      vars:
        build_dir_base: "{{ base_dir }}/docker_build"
        build_subdir_name: "DeathStar-workload-{{ timestamp }}"
        build_subdir: "{{ build_dir_base }}/{{ build_subdir_name }}"
        dockerfile_source: Dockerfile.workload
        files_to_copy:
          - src: "{{ base_dir }}/application-demos/DeathStarBench/wrk2/"
            dest: "{{ build_subdir }}/wrk2/"
            mode: "0755"
          - src: "{{ base_dir }}/application-demos/DeathStarBench/socialNetwork/wrk2/scripts/social-network/"
            dest: "{{ build_subdir }}/social-network/"
            mode: "0755"
          - src: "{{ luarocks_tar }}"
            dest: "{{ build_subdir }}/"
            mode: "0755"

    - name: Get nginx-thrift service IP
      command: kubectl get svc nginx-thrift -o jsonpath='{.spec.clusterIP}'
      register: nginx_thrift_ip

    - debug:
        msg: "Nginx-thrift service IP: {{ nginx_thrift_ip.stdout }}"

    - name: Render Kubernetes Pod template
      template:
        src: k8s_pod_workload.yaml.j2
        dest: "{{ job_yaml_path }}" 

    - name: Create Kubernetes Pod
      shell: kubectl apply -f {{ job_yaml_path }}

    - name: Get the name of the first pod in the deployment
      shell: "kubectl get pods -l app={{ job_name }} -o jsonpath='{.items[0].metadata.name}'"
      register: pod_name

    - name: Display the pod name
      debug:
        msg: "Pod name is {{ pod_name.stdout }}"
      
    - debug: 
        msg: 
          - "kubectl exec -it {{ pod_name.stdout }} -- /bin/sh"
          - "# Compose posts"
          - "./wrk -D exp -t 8 -c 16 -d 10 -L -s ../social-network/compose-post.lua http://{{ nginx_thrift_ip.stdout }}:8080/wrk2-api/post/compose -R 100"
          - "# Read home timelines"
          - "./wrk -D exp -t 8 -c 16 -d 10 -L -s ../social-network/read-home-timeline.lua http://{{ nginx_thrift_ip.stdout }}:8080/wrk2-api/home-timeline/read -R 100"
          - "# Read user timelines"
          - "./wrk -D exp -t 8 -c 16 -d 10 -L -s ../social-network/read-user-timeline.lua http://{{ nginx_thrift_ip.stdout }}:8080/wrk2-api/user-timeline/read -R 100"