---
- name: Ensure v2ray service is stopped and disabled
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Stop v2ray service
      service:
        name: v2ray
        state: stopped
        enabled: no
...