---
- name: Download and install sealos
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Download sealos
      get_url:
        url: https://github.com/labring/sealos/releases/download/v4.3.7/sealos_4.3.7_linux_amd64.tar.gz
        dest: /tmp/sealos_4.3.7_linux_amd64.tar.gz
        timeout: 600
      environment:
        http_proxy: "{{ hostvars['main']['proxy'] }}"
        https_proxy: "{{ hostvars['main']['proxy'] }}"

    - name: Extract sealos
      unarchive:
        src: /tmp/sealos_4.3.7_linux_amd64.tar.gz
        dest: /tmp/
        creates: /tmp/sealos

    - name: Ensure sealos is executable
      file:
        path: /tmp/sealos
        mode: '0755'
        state: file

    - name: Move sealos to /usr/bin
      command: mv /tmp/sealos /usr/bin/sealos

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install package uidmap
      apt:
        name: uidmap
        state: present

    - name: Install package fuse-overlayfs
      apt:
        name: fuse-overlayfs
        state: present

- name: Install kubernetes via sealos
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Set sealos command
      set_fact:
        sealos_command: |
          sealos run registry.cn-shanghai.aliyuncs.com/labring/kubernetes:v1.24.17 \
          registry.cn-shanghai.aliyuncs.com/labring/helm:v3.13.2 \
          registry.cn-shanghai.aliyuncs.com/labring/flannel:v0.19.2 \
          --masters {{ hostvars['main']['ansible_host'] }} \
          --nodes {% for host in groups['workers'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %} \
          --pk '{{ hostvars['main']['ssh_key'] }}' \
          --passwd '{{ hostvars['main']['ansible_become_pass'] }}' \
          --user {{ hostvars['main']['ansible_user'] }}

    - name: Debug sealos command
      debug:
        msg: "{{ sealos_command }}"

    - name: Check current user
      command: whoami
      register: whoami_output

    - name: Debug current user
      debug:
        msg: "Current user is {{ whoami_output.stdout }}"
        
    - name: Run sealos command
      shell: "{{ sealos_command }}"
      args:
        executable: /bin/bash
      environment:
        http_proxy: "{{ hostvars['main']['proxy'] }}"
        https_proxy: "{{ hostvars['main']['proxy'] }}"

- name: Install kubernetes via sealos
  hosts: controller
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure /etc/kubernetes/admin.conf is readable by all users
      file:
        path: /etc/kubernetes/admin.conf
        owner: root
        group: root
        mode: '0644'
        state: file
...