- name: Install bpftools on all nodes
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install dependencies for bpftools
      apt:
        name:
          - binutils-dev
          - libcap-dev
        state: present

    - name: Check if old libbpf directory exists
      stat:
        path: "/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools/libbpf"
      register: old_libbpf_dir

    - name: Remove old libbpf directory if it exists
      file:
        path: "/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools/libbpf"
        state: absent
      when: old_libbpf_dir.stat.exists

    - name: Create symbolic link for libbpf
      file:
        src: "/home/{{ ansible_user }}/microservice-failure-analysis/deps/libbpf/libbpf"
        dest: "/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools/libbpf"
        state: link
        force: yes

    - name: Checkout specific version v7.2.0
      command: git checkout tags/v7.2.0
      args:
        chdir: '/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools'
      register: checkout_result

    - name: Verify bpftool version
      command: git describe --tags
      args:
        chdir: '/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools'
      register: bpftool_version

    - name: Print the checked out version
      debug:
        msg: "Checked out bpftool version: {{ bpftool_version.stdout }}"

    - name: Build bpftool
      shell: make && make install
      args:
        chdir: "/home/{{ ansible_user }}/microservice-failure-analysis/deps/bpftools/bpftools/src"
        executable: /bin/bash

    - name: Check bpftool installation
      command: bpftool --version
      register: bpftool_version
      failed_when: "'command not found' in bpftool_version.stderr"
 
    - name: Verify bpftool installation
      debug:
        msg: "bpftool installed successfully."
...