---
- name: Ensure repo is updated on workers
  hosts: workers
  become: no  # 使用root权限执行
  gather_facts: no  # 不收集主机信息
  vars_files:
    - shared_vars.yaml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install git incase it is not installed
      apt:
        name: git
        state: latest

    - name: Pull the latest update from feature/gearbox
      git:
        repo: 'https://github.com/netsyscode/microservice-failure-analysis'
        dest: "{{ base_dir }}"
        version: 'feature/gearbox'
        force: yes
        update: yes  # 拉取最新的代码
      register: git_result
      until: git_result is succeeded
      retries: 5
      delay: 10
      environment:
        http_proxy: "{{ proxy }}"
        https_proxy: "{{ proxy }}"

- name: Ensure submodule is updated on all nodes
  hosts: all
  become: no
  gather_facts: no
  vars_files:
    - shared_vars.yaml
  tasks:
    - name: Update git submodules
      command: git submodule update --init
      args:
        chdir: "{{ base_dir }}"
      register: submodule_result
      until: submodule_result is succeeded
      retries: 5
      delay: 10
      environment:
        http_proxy: "{{ proxy }}"
        https_proxy: "{{ proxy }}"
...