apiVersion: v1
kind: Namespace
metadata:
  name: loadgen

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
  namespace: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: datawine/loadgen:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
